[window]
opacity = 0.9

[font]
normal = { family = "IosevkaTerm Nerd Font", style = "Regular" }
size = 24

[colors]
draw_bold_text_with_bright_colors = true


[env]
TERM = "xterm-256color"

[general]
import = [
  # uncomment the flavour you want below:
  "~/.config/alacritty/catppuccin-mocha.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-latte.toml"
]
